language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install: pip install .
before_script:
  - pip install -r tests/requirements.txt --use-mirrors
script:  coverage run --source=django_pastedeploy_settings setup.py test
after_success:
  - coveralls
